//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMediaService")]
    public interface IMediaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaService/Play", ReplyAction="http://tempuri.org/IMediaService/PlayResponse")]
        bool Play(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaService/PlayByFont", ReplyAction="http://tempuri.org/IMediaService/PlayByFontResponse")]
        bool PlayByFont(string content, int fontSizeIndex, int fontColorIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMediaServiceChannel : Website.ServiceReference1.IMediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediaServiceClient : System.ServiceModel.ClientBase<Website.ServiceReference1.IMediaService>, Website.ServiceReference1.IMediaService {
        
        public MediaServiceClient() {
        }
        
        public MediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Play(string content) {
            return base.Channel.Play(content);
        }
        
        public bool PlayByFont(string content, int fontSizeIndex, int fontColorIndex) {
            return base.Channel.PlayByFont(content, fontSizeIndex, fontColorIndex);
        }
    }
}
